### ISSUE TITLE
Full width responsive 

### ISSUE THREAD

**Issue by waridev** [bodrovis/RadiantScroller#2]
Hi, 
I need to make it full width of screen and responsive to I used % but its not working for me please help me do solve this

**Comment by bodrovis** [comment]
@warisarain Unfortunately, I do not think this is possible - this feature is not implemented. I am not maintaining the library for quite a long time as very few people actually use it (I created it for only one of my projects and have no need for it as well). I might try to add this feature for you, but can't guarantee anything.
